db.driver.Class=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://172.23.44.210:3306/legal_chatbot?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
db.username=legal
db.password=Legal1234!

jwt.secret=legalRagChatbotSecretKeyForJwtToken2024!!
jwt.expiration=86400000